import "./globals.css";
import { Inter as FontSans } from "next/font/google";

import { cn } from "@/lib/utils";

export const fontSans = FontSans({
    subsets: ["cyrillic", "latin"],
    variable: "--font-sans",
});

export const metadata = {
    title: "Test Work Valantis",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="ru">
            <body
                className={cn(
                    "min-h-screen bg-background font-sans antialiased",
                    fontSans.variable
                )}
            >
                {children}
            </body>
        </html>
    );
}
